import React from "react";
import Head from "next/head";

const Meta = () => {
  return (
    <Head>
      <title>TACSFON FUNAAB</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/logo.png' />
      <link rel='stylesheet' href='https://use.typekit.net/eeb3wag.css' />
    </Head>
  );
};

export default Meta;
